apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: loki
  namespace: monocle
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: loki
  chart:
    repository: https://grafana.github.io/loki/charts
    name: loki
    version: 0.23.0
  values:
    loki:
      enabled: true
    grafana:
      enabled: true
      sidecar:
        datasources:
          enabled: true
    prometheus:
      enabled: true
    promtail:
      enabled: true
