---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: betamax
  name: betamax

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: duckdns
  name: duckdns

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: traefik
  name: traefik

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: metallb
  name: metallb-system

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: monocle
  name: monocle

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: kafka
  name: kafka

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: chaos
  name: chaos

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: heimdall
  name: heimdall

# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   labels:
#     app: db
#   name: db
