---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: betamax
  name: betamax

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: duckdns
  name: duckdns

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: traefik
  name: traefik

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: letsencrypt
  name: letsencrypt
