apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kubewatch
  namespace: monocle
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: kubewatch
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 1.0.9
    name: kubewatch
  values:
    slack:
      enabled: false
    webhook:
      enabled: true
      url: "https://hooks.slack.com/services/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"
      namespaceToWatch: ""
      resourcesToWatch:
        deployment: true
        replicationcontroller: false
        replicaset: false
        daemonset: false
        services: false
        pod: true
        job: false
        persistentvolume: false
