---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: duckdns
  name: duckdns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: duckdns
  namespace: duckdns
  labels:
    app: duckdns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: duckdns
  template:
    metadata:
      labels:
        app: duckdns
    spec:
      containers:
      - name: duckdns
        image: linuxserver/duckdns:latest
        env:
        - name: TZ
          value: Europe/Copenhagen
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: duckdns
              key: TOKEN
        - name: SUBDOMAINS
          valueFrom:
            secretKeyRef:
              name: duckdns
              key: SUBDOMAINS