---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  namespace: betamax
  labels:
    app: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
      - name: transmission
        image: linuxserver/transmission:latest
        ports:
        - name: web
          containerPort: 9091
        - name: torrent
          containerPort: 51413
        volumeMounts:
        - name: config
          mountPath: "/config"
        - name: watch
          mountPath: "/watch"
        - name: downloads
          mountPath: "/downloads"
        env:
        - name: TZ
          value: Europe/Copenhagen
        - name: USER
          value: admin
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: transmission
              key: PASSWORD
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: transmission-config
      - name: watch
        persistentVolumeClaim:
          claimName: transmission-watch
      - name: downloads
        persistentVolumeClaim:
          claimName: transmission-downloads

---
apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: betamax
spec:
  type: ClusterIP
  selector:
    app: transmission
  ports:
  - name: web
    protocol: TCP
    port: 9091
    targetPort: web

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config
  namespace: betamax
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-watch
  namespace: betamax
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-downloads
  namespace: betamax
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi