---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
  namespace: heimdall
  labels:
    app: heimdall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      containers:
        - name: heimdall
          image: linuxserver/heimdall:latest
          ports:
          - name: web
            containerPort: 80
          volumeMounts:
          - name: config
            mountPath: "/config"
          env:
            - name: TZ
              value: Europe/Copenhagen
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: heimdall-config

---
apiVersion: v1
kind: Service
metadata:
  name: heimdall
  namespace: heimdall
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.246
  selector:
    app: heimdall
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: web

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-config
  namespace: heimdall
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
