apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_datasource: "1"
  name: jaeger-datasource
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Jaeger
      type: jaeger
      access: browser
      url: http://localhost:16686
      editable: false
