apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monocle
  labels:
    grafana_datasource: "1"
  name: jaeger-datasource
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Jaeger
      type: jaeger
      access: browser
      url: http://localhost:16686
      editable: false

    #- name: Loki-jaeger
      #type: loki
      #access: proxy
      #url: http://loki-stack:3100
      #editable: false
      #isDefault: false
      #jsonData:
        #derivedFields:
          #- datasourceName: Jaeger
            #matcherRegex: "traceID=(\\w+)"
            #name: TraceID
            #url: "http://localhost:16686/trace/${__value.raw}"
