 apiVersion: helm.fluxcd.io/v1
 kind: HelmRelease
 metadata:
   name: loki-stack
   namespace: monocle
   annotations:
     flux.weave.works/automated: "true"
 spec:
  releaseName: loki-stack
  chart:
    repository: https://grafana.github.io/loki/charts
    name: loki-stack
    version: 0.27.1
  values:
    loki:
      enabled: true
      config:
        table_manager:
          retention_deletes_enabled: true
          retention_period: 168h

    grafana:
      enabled: true
      sidecar:
        datasources:
          enabled: true
      admin:
        existingSecret: "loki-stack"
        userKey: admin-user
        passwordKey: admin-password
      # persistence:
      #   enabled: true
      #   size: 1Gi
      grafana.ini:
        auth.anonymous:
          enabled: true
        metrics:
          enabled: true
        server:
          domain: wcarlsen.duckdns.org
          root_url: "https://%(domain)s/grafana"

    prometheus:
      enabled: true
      pushgateway:
        enabled: false
        server:
          retention: "7d"

    promtail:
      enabled: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monocle
spec:
  entrypoints:
  - https
  routes:
  - match: Host(`wcarlsen.duckdns.org`) && PathPrefix(`/grafana`)
    kind: Rule
    services:
    - name: loki-stack-grafana
      port: 80
    # middlewares:
    # - name: traefik-auth
    #   namespace: traefik
  tls:
    certResolver: default