---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monocle
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: loki-stack
  chart:
    repository: https://grafana.github.io/loki/charts
    name: loki-stack
    version: 0.23.0
  values:
    loki:
      enabled: true
    grafana:
      image:
        repository: grafana/grafana-dev
        tag: explore-trace-ui-demo-361f5781fb069efc345c9efdb315f014300e6ac1
      enabled: true
      sidecar:
        datasources:
          enabled: true
    prometheus:
      enabled: true
    promtail:
      enabled: true
