---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
  labels:
    app: pihole
  annotations:
    fluxcd.io/ignore: true
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        ports:
        - name: 53tcp
          protocol: tcp
          containerPort: 53
        - name: 53udp
          protocol: udp
          containerPort: 53
        - name: 67udp
          protocol: udp
          containerPort: 67
        - name: 80udp
          protocol: udp
          containerPort: 80
        - name: 443tcp
          protocol: tcp
          containerPort: 443
        volumeMounts:
        - name: pihole
          mountPath: "/etc/pihole"
        - name: dnsmasq
          mountPath: "/etc/dnsmasq.d"
        env:
        - name: TZ
          value: "Europe/Copenhagen"
      volumes:
      - name: pihole
        persistentVolumeClaim:
          claimName: pihole
      - name: dnsmasq
        persistentVolumeClaim:
          claimName: dnsmasq

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole
  namespace: pihole
  annotations:
    fluxcd.io/ignore: true
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dnsmasq
  namespace: pihole
  annotations:
    fluxcd.io/ignore: true
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi