---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  namespace: betamax
  labels:
    app: jackett
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
        - name: jackett
          image: linuxserver/jackett:latest
          ports:
          - name: web
            containerPort: 9117
          volumeMounts:
          - name: config
            mountPath: "/config"
          # - name: downloads
          #   mountPath: "/downloads"
          env:
            - name: TZ
              value: Europe/Copenhagen
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: jackett-config
      # - name: downloads
      #   persistentVolumeClaim:
      #     claimName: transmission-downloads

---
apiVersion: v1
kind: Service
metadata:
  name: jackett
  namespace: betamax
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.245
  selector:
    app: jackett
  ports:
  - name: web
    protocol: TCP
    port: 9117
    targetPort: web

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-config
  namespace: betamax
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
