apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-auth
  namespace: traefik
spec:
  basicAuth:
    secret: traefik-users

---
kind: Middleware
metadata:
  name: grafana-stripprefix
  namespace: traefik
spec:
  stripPrefix:
    prefixes:
      - /grafana