---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: chaoskube
  namespace: chaos
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: chaoskube
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: chaoskube
    version: 3.1.3
  values:
    labels: app!=plex
    namespaces: '!kube-system,!metallb-system,!traefik'
    logFormat: 'json'
    minimumAge: 1h
    metrics:
      enabled: true
      servicemonitor:
        enabled: true
