apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monocle
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: influxdb
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 4.3.2
    name: influxdb
  values:
    persistence:
        size: 4Gi
    config:
        retention:
            enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"