apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monocle
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: influxdb
  chart:
    repository: https://helm.influxdata.com/
    version: 4.4.3
    name: influxdb
  values:
    persistence:
      size: 4Gi
    config:
      retention:
        enabled: true
        check-interval: "30m0s"
      http:
        write-tace: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8086"
    initScripts:
      enabled: true
      scripts:
        init.iql: |+
          CREATE DATABASE "prometheus" WITH DURATION 7d REPLICATION 1
