apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: speedtest
  name: speedtest
  namespace: monocle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest
  template:
    metadata:
      labels:
        app: speedtest
    spec:
      containers:
      - image: jraviles/prometheus_speedtest:latest
        name: prometheus-speedtest-jrfrw
        ports:
        - name: probe
          containerPort: 9516

---
apiVersion: v1
kind: Service
metadata:
  name: speedtest
  namespace: monocle
spec:
  type: ClusterIP
  selector:
    app: speedtest
  ports:
  - name: probe
    protocol: TCP
    port: 9516
    targetPort: 9516