---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux-web
  namespace: flux
spec:
  releaseName: flux-web
  chart:
    git: git@github.com:flux-web/flux-web.git
    path: chart/flux-web
    ref: master
  values:
    frontend:
        env:
          API_EXTERNAL_URL: //flux-web-backend/api/v1
          WS_URL: wss://flux-web-backend/ws/v1
    ingress:
      hosts:
        - host: flux-web.my-domain
          paths: 
            - frontend: /
            - backend: /api
            - backend: /ws
