---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux-web
  namespace: flux
spec:
  releaseName: flux-web
  chart:
    git: git@github.com:flux-web/flux-web.git
    path: chart/flux-web
    ref: master
  values:
    frontend:
        env:
          API_EXTERNAL_URL: //wcarlsen.duckdns.org/flux-backend/api/v1
          WS_URL: wss://wcarlsen.duckdns.org/flux-backend/ws/v1
    ingress:
      hosts:
        - host: wcarlsen.duckdns.org
          paths:
            - frontend: /
            - backend: /api
            - backend: /ws
    readOnly: "true"

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: flux-backend
  namespace: flux
spec:
  entrypoints:
  - https
  routes:
  - match: Host(`wcarlsen.duckdns.org`) && PathPrefix(`/flux-backend`)
    kind: Rule
    services:
    - name: flux-web-backend
      port: 80
    middlewares:
    - name: traefik-auth
      namespace: traefik
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: flux-frontend
  namespace: flux
spec:
  entrypoints:
  - https
  routes:
  - match: Host(`wcarlsen.duckdns.org`) && PathPrefix(`/flux`)
    kind: Rule
    services:
    - name: flux-web-frontend
      port: 80
    middlewares:
    - name: traefik-auth
      namespace: traefik
  tls:
    certResolver: default
