---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kafka
  namespace: kafka
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: kafka
  chart:
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
    name: kafka
    version: 0.20.8
  values:
    replicas: 1
    zookeeper:
      replicaCount: 1
    persistence:
      enabled: true
      size: 1Gi
    topics:
    - name: dev
      partitions: 1
      config: "cleanup.policy=compact,delete.retention.ms=86400000"
    - name: prod
      partitinos: 1
      config: "cleanup.policy=compact,delete.retention.ms=604800000"
    prometheus:
      kafka:
        enabled: true
    external:
      enabled: true
      type: LoadBalancer
      distinct: false
      loadBalancerIP: [192.168.1.249]
    configurationOverrides:
      ## Options required for external access via NodePort
      ## ref:
      ## - http://kafka.apache.org/documentation/#security_configbroker
      ## - https://cwiki.apache.org/confluence/display/KAFKA/KIP-103%3A+Separation+of+Internal+and+External+traffic
      ##
      ## Setting "advertised.listeners" here appends to "PLAINTEXT://${POD_IP}:9092,", ensure you update the domain
      ## If external service type is Nodeport:
      # "advertised.listeners": |-
      #   EXTERNAL://kafka.cluster.local:$((31090 + ${KAFKA_BROKER_ID}))
      ## If external service type is LoadBalancer and distinct is true:
      # "advertised.listeners": |-
      #   EXTERNAL://kafka-$((${KAFKA_BROKER_ID})).cluster.local:19092
      ## If external service type is LoadBalancer and distinct is false:
      "advertised.listeners": |-
        EXTERNAL://${LOAD_BALANCER_IP}:31090
      ## Uncomment to define the EXTERNAL Listener protocol
      "listener.security.protocol.map": |-
        PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT