---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kafka
  namespace: kafka
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: kafka
  chart:
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
    name: kafka
    version: 0.20.8
  values:
    replicas: 1
    zookeeper:
      replicaCount: 1
    persistence:
      enabled: true
      size: 1Gi
    topics:
    - name: test
      partitions: 1
      config: "cleanup.policy=compact,delete.retention.ms=604800000"
    prometheus:
      kafka:
        enabled: true


